service: weather

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  tracing: true
  environment:
    APP_WEATHER_KEY: ${env:APP_WEATHER_KEY}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:*
      Resource: "*"

plugins:
  - serverless-offline 
  - serverless-plugin-tracing

functions:
  weather:
    handler: src/handler.weather
    events:
      - http:
          path: weather
          method: get